---
title: "Lab 03 - Nobel laureates"
author: "Bob D"
date: "28Mar23"
output: github_document
---

### Load packages and data

```{r load-packages, message=FALSE}
library(tidyverse) 
```

```{r load-data, message=FALSE}
nobel <- read_csv("data/nobel.csv")
```

## Exercises
### Exercise 1
```{r}
#How many variables are in the dataset?
nobel %>%
  ncol()

#Each row represents a winner. Number of winners?
nobel %>%
  nrow()
```
### Exercise 2
```{r}
#Create a new data frame called nobel_living that includes only observations of living people for which country data is available. 
nobel_living <- nobel %>%
  filter(!is.na(country),gender != "org", is.na(died_date))
```

### Exercise 3
```{r}
#this takes the new variable and adds a new column. If country the laureate was living in during the price year = "USA," set country to USA, if not, set to other.
nobel_living <- nobel_living %>%
  mutate(
    country_us = if_else(country == "USA", "USA", "Other")
  )

#limit our analysis to only the following categories: Physics, Medicine, Chemistry, and Economics
nobel_living_science <- nobel_living %>%
  filter(category %in% c("Physics", "Medicine", "Chemistry", "Economics"))

#data visualization - Create a faceted bar plot visualizing the relationship between the category of prize and whether the laureate was in the US when they won the nobel prize.

nobel_living_science %>%
  ggplot(aes(x = country_us)) +
  geom_bar() +
  coord_flip() +
  facet_wrap(~ category) +
  labs(title = "Most living Nobel laureates were living in the US when they won their prizes",
       x = "Location of Nobel laureates when awared prize (in US or not)",
       y = "Number of Winners") 
```
### Exercise 4
```{r}
#Creates new variable called born_country_us to indicate laureate who is US born (or not)
nobel_living_science <- nobel_living_science %>%
  mutate(
    born_country_us = if_else(born_country == "USA", "USA", "Other")
  )

#How many of the winners are born in the US?
nobel_living_science %>%
  group_by(born_country_us) %>%
  summarize(n = n())
#105 Nobel laureates in the Physics, Medicine, Chemistry, and Economics fields were born in the US (123 outside of US)
```

### Exercise 5
```{r}
#Data visualization
nobel_living_science %>%
  ggplot(aes(x = country_us,fill = born_country_us)) +
  geom_bar() +
  coord_flip() +
  facet_wrap(~ category) +
  labs(title = "Most living Nobel laureates were living in the US when they won their prizes",
       x = "Location of Nobel laureates when awared prize (in US or not)",
       y = "Number of Winners",
       caption = "Color represent whether US born (blue) or not (orange")

#Based on your visualization, do the data appear to support Buzzfeed’s claim?
#Claim 1: Most living Nobel laureates were based in the US when they won their prizes.
#Claim 2: But of those US-based Nobel laureates, many were born in other countries.
#More living laureates were indeed living with the US when they won their prize; however, there were more laureates who were living in the US 
#when they won their prize were also born US born.
```

### Exercise 6
```{r}
nobel_living_science %>%
  filter(country == "USA", born_country_us == "Other") %>%
  count(born_country) %>%
  arrange(desc(n))
#Germany and the UK have the most laureates that won their award in the US, but were born outside of the US.
```
